### ISSUE TITLE
[Bug]: Console build fails: missing "monaco-editor" type declarations in TabbedEditor.tsx

### ISSUE THREAD

**Issue by tudan110** [agentscope-ai/QwenPaw#4700]
### Describe the bug

Running `pnpm run build` in the `console/` directory fails with TypeScript errors:

```sh
src/pages/Coding/TabbedEditor.tsx:19:45 - error TS2307: Cannot find module 'monaco-editor' or its corresponding type declarations.

19 import type { editor as MonacoEditor } from "monaco-editor";
                                               ~~~~~~~~~~~~~~~

src/pages/Coding/TabbedEditor.tsx:292:42 - error TS7006: Parameter 'e' implicitly has an 'any' type.

292       editor.onDidChangeCursorSelection((e) => {
                                             ~


Found 2 errors.
```

 ### Root Cause

 `TabbedEditor.tsx` (introduced in #4578) imports types directly from `"monaco-editor"`, but only `@monaco-editor/react` is listed in `package.json`. The `monaco-editor` package itself is not declared as a dependency, so its type declarations are unavailable during `tsc -b`.

 Additionally, the `onDidChangeCursorSelection` callback parameter `e` lacks an explicit type annotation, which fails under `noImplicitAny`.

 ### Steps to Reproduce

  1. Fresh clone
  2. `cd console && pnpm install && pnpm run build`

 ### Expected Behavior

 Build succeeds without errors.

 ### Suggested Fix

  1. Add `monaco-editor` as a devDependency: `pnpm add -D monaco-editor`
  2. Add type annotation: `editor.onDidChangeCursorSelection((e: MonacoEditor.ICursorSelectionChangedEvent) => {`

 ### Environment
 - Node: v22
 - pnpm: 11.2.2
 - OS: macOS (Darwin)

**Comment by rayrayraykk** [comment]
Have you run `npm ci` or `npm install`?

**Comment by Chris79OG** [comment]
I checked current `main` on Windows against the package files in `console/`.

What I found:

- `console/` has `package-lock.json` and no `pnpm-lock.yaml`, so I used the repo's npm path.
- `npm install --ignore-scripts` installs `monaco-editor@0.55.1` through `@monaco-editor/react@4.7.0`'s peer dependency.
- `npm ls monaco-editor --depth=1` shows:

```text
qwenpaw-console@0.0.0
`-- @monaco-editor/react@4.7.0
  `-- monaco-editor@0.55.1
```

- `npm run build` does not reproduce the two reported `TabbedEditor.tsx` errors on current `main`; TypeScript gets past that file and fails later on existing unrelated type gaps in `MermaidCodeBlock`, `Heartbeat`, `AgentStats`, `usePluginManager`, and `TokenUsage`.

So this looks package-manager/install-state specific rather than a current missing direct dependency in `TabbedEditor.tsx`. If the intended supported path is pnpm, the console package likely needs a committed `pnpm-lock.yaml` or package-manager note; otherwise the reporter should retry with npm from a clean checkout.

**Comment by tudan110** [comment]
Thank you for the clarification. It's confirmed that npm is resolved through peerDependency of @monaco-editor/react, and the Docker build uses npm ci --legacy-peer-deps, so it won't be affected.

However, if pnpm is used by default, it won't automatically install peer dependencies, leading to build failures. Adding "monaco-editor" to devDependencies can resolve the issue for pnpm users without affecting the npm workflow.

Would the team be willing to add this devDependency to package.json?

**Comment by lalaliat** [comment]
Thank you for your feedback. Since adding it again would duplicate a peer-managed dependency and introduce the risk of version drift, we plan not to include it at this time. Thank you.
